### ISSUE TITLE
Cannot Cut Car

### ISSUE THREAD

**Issue by TripleShades** [LoneStarF13/LoneStar#143]
## Reproduction:
Slap car with turned on welder.
Car cannot be cut into.
Become very sad.
![image](https://user-images.githubusercontent.com/6299921/148156380-fec5fd15-8cb1-4fef-a8c6-e6ff0a64240f.png)
![image](https://user-images.githubusercontent.com/6299921/148156277-e775eef0-6909-4a0c-932b-1c4226cc8cc5.png)

**Comment by Cythisiax** [comment]
non issue, some vehicles can't be cut/salvaged
