### ISSUE TITLE
Grognak Big_Leagues

### ISSUE THREAD

**Issue by TripleShades** [LoneStarF13/LoneStar#174]
## Reproduction:
Read Grognak
![image](https://user-images.githubusercontent.com/6299921/149225638-ff7341aa-9f4e-476b-8c47-4943b7e40f37.png)

**Comment by Cythisiax** [comment]
fixed

#define TRAIT_BIG_LEAGUES		"big leagues"

**Comment by TripleShades** [comment]
Just realized you didn't actually fix any of these so I'm reopening them.
