### ISSUE TITLE
Tribals getting hallucinations from powder

### ISSUE THREAD

**Issue by VEN0M5** [LoneStarF13/LoneStar#200]
## Testmerges:

Round ID: 836
BYOND Version: 514.1571
Server revision compiled on: 2022-01-17T05:46:50+00:00
Master commit: 17c5484f2c7fb6d02c8e08632c25da387e870556
The following pull requests are currently test merged:
#177: 'propaganda eye bot is silent now' by cornercube at commit f457e8db90
#182: 'Dirt adjust' by Pebblesthe2nd at commit ea5b9f36b4
#188: 'Full Auto' by Tron-117 at commit deb7cbcf8b
#191: 'hasty coconut bomb disable' by zulixe at commit c3007891f2
#168: 'quick and dirty armor change, death to linearmor' by cornercube at commit af8c44e807

Local commit: 50de044be4540b0d388ea71acec57a8067992e10
TGS version: 4.15.7
DMAPI version: 5.3.0

## Reproduction:

Tribals should be benefiting fully from the tribal healing items such as powder and bitter drinks. Instead I was getting hallucinations when using powder as a tribal so I assumed that the associated trait was gone.

**Comment by somah69** [comment]
what role were u?

**Comment by Jaaackx** [comment]
Is this a bug or was it an intentional choice thing? Seems kinda tribal to be tripping balls on healing medicine to me.

**Comment by VEN0M5** [comment]
Issue is, the same trait that handles tripping balls also handles the extra healing that tribals should benefit from powder. So currently tribals are not getting that extra healing.

**Comment by VEN0M5** [comment]
Issue is, the same trait that handles tripping balls also handles the extra healing that tribals should benefit from powder. So currently tribals are not getting that extra healing.
