### ISSUE TITLE
Follower medical vendor vends the wrong med hud

### ISSUE THREAD

**Issue by VEN0M5** [LoneStarF13/LoneStar#224]
## Testmerges:

Round ID: 862
BYOND Version: 514.1571
Server revision compiled on: 2022-01-20T14:43:21+00:00
Master commit: 56f527572356fdd77e27e91dddb5b246b4e86469
The following pull requests are currently test merged:
#172: 'Removes most dense rock from the surface map' by XElectricX at commit 880c4984c8
#185: 'oasis prepares for war' by cornercube at commit 58e8f2478d
#196: 'Ports Colormates (take 2) [Ready to Test Merge]' by TripleShades at commit f954e45e15
#193: 'UI alpha adjust' by Pebblesthe2nd at commit 35e9980607
#199: 'Mob organize' by Pebblesthe2nd at commit a2a7d51eda
#198: 'easy pete delivers some dynamite to yuma' by cornercube at commit 56d49cdf58
#213: 'hides lewd stuff + mkultra no longer available through chem' by Jaaackx at commit ae5c23eba5

Local commit: 6c0b4e82b719ca1fd5f59280d192294e037a6bb8
TGS version: 4.15.7
DMAPI version: 5.3.0
## Reproduction:

The top item is what was vended from the follower's vendor for 500 caps and is unusable and have no sprites.

the bottom medical hud is the one we normally use.

![image](https://user-images.githubusercontent.com/15703585/150605040-bf3b701b-c04e-483e-ae02-438812d211ce.png)

**Comment by Jaaackx** [comment]
@VEN0M5 This can be closed, someone PR'd it already but decided not to link the issue (😠). Should be fixed.
