### ISSUE TITLE
Z-Level and Surface Lighting Issue

### ISSUE THREAD

**Issue by CaputCapital** [LoneStarF13/LoneStar#51]
## Reproduction:

You have to enter a ladder down to the z-level, then come back up after a certain amount of time has passed. If the surface level appears night/pitch black and the walls appear lit, then the bug is successfully reproduced.

One way to undo this bug in game is by looking up or down the ladder, depending on whether you're on the z-level or not. Another method of undoing this bug in game involves taking the ladder back down to the z-level and taking the ladder back up.

https://cdn.discordapp.com/attachments/921220864643579975/924444431518674954/Lighting_Graphic_Bug.mp4

## Existence:
This bug has existed since Fortune13.

**Comment by buffyuwu** [comment]
interesting

**Comment by buffyuwu** [comment]
https://i.imgur.com/7fMuW2E.gif

i can't seem to reproduce this on live. it may have been a temporary bug already fixed! can you confirm if it still occurs?

**Comment by CaputCapital** [comment]
> ![image](https://camo.githubusercontent.com/3c4a65d4823c472c9193cf8005e2b21492d0ed950d51584fe364ccfda006e28d/68747470733a2f2f692e696d6775722e636f6d2f37664d755732452e676966)
> 
> i can't seem to reproduce this on live. it may have been a temporary bug already fixed! can you confirm if it still occurs?

It doesn't work like that, Buffy. You have to be on the z-level for a specific amount of time for this bug to trigger (it may be that time has to advance), I have reason to believe that it occurs if you're on the z-level for a specific amount of time.

From the GIF, this bug wasn't properly reproduced.

**Comment by OneOneThreeEight** [comment]
can't reproduce.
