### ISSUE TITLE
putting wood planks on a vent nest becomes an error

### ISSUE THREAD

**Issue by Serxule** [LoneStarF13/LoneStar#80]
## Reproduction: put wood planks onto a floor vent nest, the wood planks become an error sign
 
![image](https://user-images.githubusercontent.com/64584757/147794580-4ac5b790-7a58-4e9f-ae7f-d8054749209e.png)

**Comment by buffyuwu** [comment]
cannot reproduce, this may have been an error from a testmerge!

![image](https://user-images.githubusercontent.com/42501819/148447910-5fef455b-d1c1-4838-abae-9000d2566309.png)


feel free to re-open the issue if you come across it and do let us know where you encounter a bug if you do :D

thank you!!!!!
