### ISSUE TITLE
Khan frequency

### ISSUE THREAD

**Issue by TripleShades** [LoneStarF13/LoneStar#89]
## Reproduction:
Try and use .a to talk on khan comms.
Fail.
Use .h to talk on "head" comms.
It works.
????
![image](https://user-images.githubusercontent.com/6299921/147844832-0ebfc6c4-e9db-469e-bff0-dcdb417ddde8.png)

**Comment by Cythisiax** [comment]
desc = "An encryption key for a radio headset.  To access the Khan channel, use :h."

fixed

**Comment by TripleShades** [comment]
Not sure I'd call that fixed, but it works.

**Comment by Cythisiax** [comment]
I mean it literally states, :a does not work, fail

:h is also by default your radio command for all headsets, I have made it state :h instead of :a

**Comment by TripleShades** [comment]
This means that Khans don't have an alternate frequency, which means that, should another person get their comms key for whatever reason, they cannot directly talk into it if they have multiple keys.

**Comment by Cythisiax** [comment]
You can only have 1 encryption key per headset, you can't take them out anymore.

**Comment by TripleShades** [comment]
Oh, my bad then. I guess this is fine.

**Comment by TripleShades** [comment]
Just realized you didn't actually fix any of these so I'm reopening them.
